version: '2'
services:
    front:
      image: nginx
      ports:
        - "80:80"
      links:
        - app
      volumes:
        - "./:/var/www"
        - "./docker/nginx/vhost/laravel_vhost:/etc/nginx/conf.d/default.conf:ro"
    app:
      build: .
      links:
        - mariadb
        # - tempdash_elasticsearch
      volumes:
        - "./docker/php/php.ini:/usr/local/etc/php/conf.d/030-custom.ini:ro"
        - "./:/var/www"
      ports:
        - "9000:9000"
      environment:
        - "DB_HOST=mariadb"
        - "DB_PORT=3306"
        - APP_ENV=dev
        - APP_DEBUG=1
        - APP_SECRET=83512d52ee8797e6e9de2322dc781885
        - DATABASE_HOST=mariadb
        - DATABASE_USER=homestead
        - DATABASE_PASSWORD=secret
        - DATABASE_NAME=homestead
        - DATABASE_PORT=3306
        - LETSENCRYPT_HOST=localhost
        - LETSENCRYPT_EMAIL=email@example.com
      working_dir: "/var/www"

    mariadb:
      image: mariadb
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      environment:
        - "MYSQL_ROOT_PASSWORD=secret"
        - "MYSQL_USER=homestead"
        - "MYSQL_PASSWORD=secret"
        - "MYSQL_DATABASE=homestead"
      ports:
        - "3306:3306"
      volumes:
        - dbdata:/var/lib/mysql

volumes:
  dbdata:

    # tempdash_elasticsearch:
    #   image: elasticsearch
    #   ports:
    #     - "9200:9200"